### ISSUE TITLE
Javascript generic list with C# LINQ style functionality

### ISSUE THREAD

**Issue by brakmic** [ericelliott/object-list#1]
I found this blog post about a library that offers LINQ-like querying of objects / lists /dictionaries.

http://codeiain.azurewebsites.net/javascript-generic-list-with-c-linq-style-functionality/

Regards,
Harris

**Comment by ericelliott** [comment]
## Thanks for the link!

My thoughts:
1. `object-list` is strictly non-destructive. It should not mutate the passed in list. Instead, it should return a new list. I didn't look at the linked source well enough to make sure none of its methods mutate.
2. Our architecture is already much more modular and flexible than that one. We're basing it on how lodash deals with modularity, so you can require just one function, or the entire API. This is helpful to reduce the size of browser bundles. 
3. Our API should be compatible with infinite streams and generators.
4. We can really improve on that API.

## Thoughts on Methods
- `.RemoveByIndex()` – functionality available on list prototype as `.filter()`, but we add something that would be an exact opposite of `.slice()` (return the filtered list instead of the sliced out subset).
- `.Remove()` – Removes an item from the collection (see above, but we should only have one method for this, not two -- the range version should default to a single item if the second range parameter is not supplied).
- `.SerializeToJSON()` – Built into JS as `JSON.stringify()`, but we could add a convenience method called `.json()` that is [a safe version that does not throw](https://github.com/isaacs/json-stringify-safe).
- `.OrderBy()`, `.OrderByDescending()` – Orders the list bases on the property passed in. Good idea. =)
- `.ElementAt()` – Returns an object from the collection at a set index.
- `.Contains()` – Currently experimental for [`Array.prototype` (ES7)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes). We _could_ surface this as [`.includes()`](https://lodash.com/docs#includes) pretty easily. 

## Already available
- `.add()` - already exists as `Array.prototype.push()` (I'm assuming that all lists passed in supply `Array.prototype` compatible interface. `.push()` does not do type enforcement (and shouldn't, it would make the library less generally useful for things like APIs). Maybe we should explicitly document the expected API, and inherit passed-in list prototype on the returned object? =)
- `.count()` - already exists as `Array.prototype.length`, but could be wrapped as a method and _should be used with caution_ for compatibility with infinite streams and generators.
- `.where()` - already exists as `.where()` in this lib. Not documented because we need a bug fix for multiple clauses.

**Comment by ericelliott** [comment]
Good ideas stolen, the rest scrapped. See [future](https://github.com/ericelliott/object-list/blob/master/docs/future.md).
